# Generated by Django 4.2.2 on 2023-11-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
    ]
